server:
  port: 9000
  
spring:  application:    name: feign-consumer  
  cloud:
    loadbalancer:
      retry:
        #开启重试机制
        enabled: true  
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
 
feign:
  hystrix:
    command: 
      default: 
       execution: 
        isolation: 
          thread: 
           timeoutInMilliseconds: 5000
  enabled: true               #打开断路器
  polling-interval-ms: 2000   #刷新间隔

    
hello-service: #服务调用的名字
  ribbon: 
    ConnectTimeout: 6000 # Ribbon的连接超时时间
    ReadTimeout: 6000 # Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: true  # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
    MaxAutoRetries: 1 # 对当前实例的重试次数
